
[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]  # Erro, pyflakes, warnings, import sorting

[tool.pyright]
include = ["app"]
exclude = ["**/__pycache__"]
pythonVersion = "3.13"
typeCheckingMode = "basic"
# Configuração específica para SQLAlchemy
reportGeneralTypeIssues = "warning"
reportOptionalMemberAccess = "warning"

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401"]